Set up architecture
AlexeyAnurin/WeatherAppInternship pull request #1
Opened 2021-03-16 16:24 UTC by AlexeyAnurin

2021-03-17 10:19 UTC, sin-al-vl requested changes

2021-03-17 10:19 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/AppConfig.kt
> +// api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=c0db866fb55ba479cb926887ea79dbce
This comment is redundant, please, remove

2021-03-17 10:19 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/WeatherApi.kt
> +    //Observable<WeatherResponse> getWeather(@Query("q") String city, @Query("APPID") String api);
This is redundant comment, please, remove

2021-03-17 10:19 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/WeatherApi.kt
> +    suspend fun getWeather(@Query("q") cityName: String, @Query("appid") apiKey: String): WeatherModel
We shouldn't force everyone, who uses this api, pass api key as a param every time. This is a part of this particular framework layer, so it should be exposed to another layer. We can discuss this personally, but long story short you need to set up api key usage in `ApiKeyInterceptor`, which will add this key as a query param to each request.

2021-03-17 10:19 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/AppModule.kt
> +
Redundant empty lines. It's acceptable to have only one empty line at the end of the file or don't have them here at all.

2021-03-17 10:19 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/NetworkModule.kt
> +    abstract fun provideWeatherDataSouce(weatherApi: WeatherApi): WeatherDataSouce*/
Please, remove. Don't leave such commented fragments of code for your future changes. As an option, you may shelve them.

2021-03-17 10:19 UTC, sin-al-vl commented on build.gradle
> +    //ext.kotlin_version = '1.5.0-M1'
Please, remove

2021-03-17 10:19 UTC, sin-al-vl commented on build.gradle
>          // in the individual module build.gradle files
Please, remove this comment

2021-03-17 10:19 UTC, sin-al-vl commented on build.gradle
>  // Top-level build file where you can add configuration options common to all sub-projects/modules.
Please, remove this comment

2021-03-17 11:03 UTC, AlexeyAnurin commented on app/build.gradle
> +    // dagger2
fixed

2021-03-17 11:03 UTC, AlexeyAnurin commented on app/build.gradle
>      androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
fixed

2021-03-17 11:04 UTC, AlexeyAnurin commented on app/build.gradle
> +    kapt "com.google.dagger:dagger-compiler:$dagger_version"
fixed

2021-03-17 11:04 UTC, AlexeyAnurin commented on app/build.gradle
>  }
fixed

2021-03-17 11:04 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/BaseFragment.kt
> +
fixed

2021-03-17 11:04 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/BaseViewModel.kt
> +}
fixed

2021-03-17 11:04 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/Result.kt
> +}
fixed

2021-03-17 11:06 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/AppConfig.kt
> +// api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=c0db866fb55ba479cb926887ea79dbce
fixed

2021-03-17 11:08 UTC, AlexeyAnurin commented on build.gradle
> +    //ext.kotlin_version = '1.5.0-M1'
fixed

2021-03-17 11:09 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/NetworkModule.kt
> +    abstract fun provideWeatherDataSouce(weatherApi: WeatherApi): WeatherDataSouce*/
fixed

2021-03-17 11:09 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/WeatherApi.kt
> +    //Observable<WeatherResponse> getWeather(@Query("q") String city, @Query("APPID") String api);
fixed

2021-03-17 11:09 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/AppModule.kt
> +
fixed

2021-03-17 11:09 UTC, AlexeyAnurin commented on build.gradle
>          // in the individual module build.gradle files
fixed

2021-03-17 11:10 UTC, AlexeyAnurin commented on build.gradle
>  // Top-level build file where you can add configuration options common to all sub-projects/modules.
fixed

2021-03-17 12:57 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/WeatherApi.kt
> +    suspend fun getWeather(@Query("q") cityName: String, @Query("appid") apiKey: String): WeatherModel
fixed

2021-03-17 12:57 UTC, AlexeyAnurin commented on app/build.gradle
> +    // dagger2
fixed

2021-03-17 12:58 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherModel.kt
> +        val name: String)
fixed

2021-03-17 15:04 UTC, AlexeyAnurin commented on app/build.gradle
> +    kapt "com.google.dagger:dagger-compiler:$dagger_version"
fixed

2021-03-17 16:02 UTC, sin-al-vl requested changes

2021-03-17 16:02 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/NetworkModule.kt
> +        interceptors.add(loggingInterceptor)
Do you feel that smth wrong here, do you?)
`LoggingInterceptor` declaration might be moved to separate file, like `ApiKeyInterceptor`. And then both of them may be provided via multibinding here.

2021-03-17 17:23 UTC, AlexeyAnurin commented on build-const.gradle
> +}
fixed

2021-03-17 17:25 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/ApiKeyInterceptor.kt
> +        val url = chain.request().url.newBuilder().addQueryParameter(API_KEY, APP_ID).build()
fixed

2021-03-17 17:47 UTC, AlexeyAnurin commented on app/build.gradle
>          applicationId "com.griddynamics.weatherapp"
I had errors when I tried to use int constants. Now I figured out, that error is related to minSdk constant.
![image](https://user-images.githubusercontent.com/48724785/111513006-06272580-8759-11eb-8353-448125f39762.png)

2021-03-18 12:02 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/NetworkModule.kt
> +        interceptors.add(loggingInterceptor)
fixed

2021-03-18 17:38 UTC, sin-al-vl requested changes

2021-03-18 17:38 UTC, sin-al-vl commented on app/build.gradle
>          applicationId "com.griddynamics.weatherapp"
Indeed, looks like viewbinding issue. Let's leave minSdkVersion without constant

2021-03-18 17:38 UTC, sin-al-vl commented on app/build.gradle
> +    buildToolsVersion "$buildTools"
This is redundant wrapping in quotes, please, remove

2021-03-18 17:38 UTC, sin-al-vl commented on app/build.gradle
> +        versionName "$version_name"
This is redundant wrapping in quotes, please, remove

2021-03-18 17:38 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/NetworkModule.kt
> +    }
Firstly, we may use binds here:
```
@Binds
@IntoSet
fun provideApiKeyInterceptor(
    interceptor: ApiKeyInterceptor
): Interceptor
```
Secondly, it'd be nice to move your interceptors providing into separate `InterceptorsModule` and then include it here, into `NetworkModule`. Maybe you implied this when told me about multibinding with multiple modules. If yes, then you were right.

2021-03-18 17:38 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/interceptors/ApiKeyInterceptor.kt
> +class ApiKeyInterceptor @Inject constructor() : Interceptor {
internal

2021-03-19 09:23 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/interceptors/ApiKeyInterceptor.kt
> +class ApiKeyInterceptor @Inject constructor() : Interceptor {
fixed

2021-03-19 09:38 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/interceptors/ApiKeyInterceptor.kt
> +class ApiKeyInterceptor @Inject constructor() : Interceptor {
fixed

2021-03-19 09:41 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/framework/di/NetworkModule.kt
> +    }
Module cant contain @Binds and @Provides at the same time. Because of that I have used in InterceptorsModule @Provides annotation for provideApiKeyInterceptor().

2021-03-19 09:43 UTC, AlexeyAnurin commented on app/build.gradle
> +    buildToolsVersion "$buildTools"
fixed

2021-03-19 09:43 UTC, AlexeyAnurin commented on app/build.gradle
> +        versionName "$version_name"
fixed

2021-03-19 15:32 UTC, sin-al-vl approved these changes

2021-03-19 15:39 UTC, merged