Tabs (Today, Tomorrow, Week), TabsNavigationFragment, TabsNavigationV…
AlexeyAnurin/WeatherAppInternship pull request #13
Opened 2021-04-02 08:31 UTC by AlexeyAnurin

…iewModel

2021-04-02 15:43 UTC, sin-al-vl requested changes

2021-04-02 15:43 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/TabsNavigationFragment.kt
> +        binding.viewpager.adapter = adapter
Let's use `ViewPager2`. Then you'll be able to extend your adapter from `FragmentStateAdapter` that makes you adapter dumb & short enough, to be an `inner class` of this fragment.
After that, you'll have a chance to get rid of a lot of boilerplate code in this fragment by creating private constant, which will be an array of `Pair`s, where you can juxtapose string res id of the tab name to the high-order function which should return `Fragment` and will simple create your ViewPager fragment instances.

2021-04-02 15:43 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/TabsNavigationViewModel.kt
> +    }
Let's save city to preferences on the main screen and then get it where it's needed

2021-04-02 15:43 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastFragment.kt
> +         })*/
...

2021-04-02 15:43 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastFragment.kt
> +    lateinit var currentWeatherForecastViewModel: CurrentWeatherForecastViewModel
It could be just `viewModel`. In each fragment. It's natural that CurrentWeatherForecastFragment uses CurrentWeatherForecastViewModel.

2021-04-02 15:43 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastViewModel.kt
> +class CurrentWeatherForecastViewModel @Inject constructor(
`current weather` and `forecast` sounds controversial. Let's omit `Forecast` in all our fragment names.

2021-04-04 14:04 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/MainActivity.kt
> +            //.add(R.id.root_frame_layout, MainScreenFragment.newInstance(), "weather")
fixed

2021-04-04 14:08 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/MainActivity.kt
> +            .add(R.id.root_frame_layout, TabsNavigationFragment.newInstance(), "weather")
Its a way to get fragment from FragmentManager by this tag.
Removed.

2021-04-04 14:14 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/di/MainActivityComponent.kt
> +    fun inject(fragment: TabsNavigationFragment)
TabsNavigationFragment renamed to MainScreenFragment

2021-04-04 14:15 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/TabsNavigationFragment.kt
> +package com.griddynamics.weatherappinternship.presentation
TabsNavigationFragment renamed to MainScreenFragment and moved to mainScreen package.

2021-04-04 14:20 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/TabsNavigationFragment.kt
> +        get() = TabsNavigationViewModel()
fixed

2021-04-04 14:29 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastFragment.kt
> +         })*/
fixed

2021-04-04 14:44 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastViewModel.kt
> +class CurrentWeatherForecastViewModel @Inject constructor(
Word "forecast" removed from fragment names.

2021-04-04 15:04 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastFragment.kt
> +    lateinit var currentWeatherForecastViewModel: CurrentWeatherForecastViewModel
All viewModels are now called "ViewModel"

2021-04-05 08:39 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/TabsNavigationViewModel.kt
> +    }
Done with Preferences DataStore & Flow.

2021-04-05 14:29 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastFragment.kt
> +    lateinit var currentWeatherForecastViewModel: CurrentWeatherForecastViewModel
I was talking about property name, not about class name. I thought it's obvious because of the lower case of the first letter in `viewModel` that i mentioned. If you do this with ViewModel class names it'll bring a lot of mess for sure!

2021-04-05 15:00 UTC, sin-al-vl requested changes

2021-04-05 15:33 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherForecastScreen/CurrentWeatherForecastFragment.kt
> +    lateinit var currentWeatherForecastViewModel: CurrentWeatherForecastViewModel
fixed

2021-04-05 16:51 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/di/RepositoryModule.kt
> +internal class DataStoreModule {
moved to CityRepositoryModule

2021-04-05 16:52 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/repository/WeatherRepository.kt
> +    suspend fun saveCityName(cityName: String)
interface CityRepository and CityRepositoryImp created

2021-04-05 16:52 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/repository/WeatherRepository.kt
> +    fun getCityNameByFlow(): Flow<String>
renamed to getCityName

2021-04-05 17:09 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +        }
moved to onViewCreated()

2021-04-05 17:18 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +    )
List of pairs moved to constant.

2021-04-06 08:02 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = USER_PREFERENCES_NAME)
Moved to CityRepositoryImpl

2021-04-06 08:06 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +}
Moved to separate file

2021-04-06 08:12 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = USER_PREFERENCES_NAME)
Moved to separate file

2021-04-06 09:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/di/RepositoryModule.kt
> +internal class DataStoreModule {
Nope. It should be moved to `DataStoreModule`. `CityRepositoryModule` may know about `DataStoreModule` only via `include`, but here with current implementation we have too strict coupling

2021-04-06 09:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = USER_PREFERENCES_NAME)
It's not enough. Preferences api should be hidden behind interface.

2021-04-06 09:19 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +    )
But why do we still need that private property `tabsFragmentList`? What state does it contain? Why we cannot use constant directly?

2021-04-06 09:24 UTC, sin-al-vl requested changes

2021-04-06 09:24 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +    private inner class TabsAdapter(fragmentActivity: FragmentActivity) : FragmentStateAdapter(fragmentActivity) {
This line is too long.

2021-04-06 09:24 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +        }*/
...........

2021-04-06 09:24 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherViewModel.kt
> +                is ResultObject.Error -> _snackBarMessage.value = result.exception?.message ?: "unknown error"
Line is too long.

2021-04-06 09:24 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherViewModel.kt
> +                is ResultObject.Error -> _snackBarMessage.value = resultHourly.exception?.message ?: "unknown error"
Line is too long.

2021-04-06 09:27 UTC, sin-al-vl requested changes

2021-04-06 09:27 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/di/CityRepositoryModule.kt
> +    ): CityRepository
`CityRepository` shouldn't be in own Dagger module. I've missed that fact earlier, but your `WeatherRepositoryModule` should be just `RepositoryModule`. And it should be responsible for providing all repos

2021-04-06 10:14 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +        }*/
fixed

2021-04-06 10:14 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +        }*/
deleted

2021-04-06 10:40 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/di/RepositoryModule.kt
> +internal class DataStoreModule {
fixed

2021-04-06 10:58 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +    )
fixed

2021-04-06 10:58 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +    private inner class TabsAdapter(fragmentActivity: FragmentActivity) : FragmentStateAdapter(fragmentActivity) {
fixed

2021-04-06 10:59 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherViewModel.kt
> +                is ResultObject.Error -> _snackBarMessage.value = result.exception?.message ?: "unknown error"
fixed

2021-04-06 10:59 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherViewModel.kt
> +                is ResultObject.Error -> _snackBarMessage.value = resultHourly.exception?.message ?: "unknown error"
fixed

2021-04-06 10:59 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/di/CityRepositoryModule.kt
> +    ): CityRepository
fixed

2021-04-06 15:41 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = USER_PREFERENCES_NAME)
fixed

2021-04-06 19:25 UTC, sin-al-vl approved these changes

2021-04-06 19:25 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/di/DataStoreModule.kt
> +}
This module is redundant. `provideDataStore()` & `provideAppDataStore()` should be in one module. Again you may refer to `NetworkModule` as an example - there is no sense in more layering here.

2021-04-07 08:36 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/di/DataStoreModule.kt
> +}
It really works with companion object!
Redundant module deleted.

2021-04-07 08:37 UTC, merged