Tomorrow forecast UI
AlexeyAnurin/WeatherAppInternship pull request #16
Opened 2021-04-07 17:13 UTC by AlexeyAnurin

![screen1](https://user-images.githubusercontent.com/48724785/113907068-9e0ab300-97dd-11eb-8cd6-dc75562b2d57.png)
![screen2](https://user-images.githubusercontent.com/48724785/113907078-9fd47680-97dd-11eb-960e-21e7d5a43b18.png)

2021-04-07 18:47 UTC, sin-al-vl approved these changes

2021-04-07 18:47 UTC, sin-al-vl commented on app/src/main/res/values/strings.xml
> +    <string name="tomorrow_humidity">Humidity</string>
Why do we need this? We already have humidity string res. It's interesting, why did you renamed `hourly_temperature_celsius_pattern` to more widely applicable name, but didn't do this to `humidity`?
I'd remove `current` prefix from all string names, except `current_atmosphere_characteristics_title', as well as remove `tomorrow` prefix from the string below.

2021-04-07 18:58 UTC, sin-al-vl requested changes

2021-04-07 18:58 UTC, sin-al-vl commented on app/src/main/res/values/colors.xml
> +    <color name="background_tab_layout">#3d91af</color>
You may reuse colors here. Create color res with direct name, like
`<color name="cyan">#3d91af</color>`
or any other suitable color name. And then you may use it here and in 13th line via `@color/cyan`

2021-04-08 11:28 UTC, AlexeyAnurin commented on app/src/main/res/values/colors.xml
> +    <color name="background_tab_layout">#3d91af</color>
fixed

2021-04-08 11:28 UTC, AlexeyAnurin commented on app/src/main/res/values/strings.xml
> +    <string name="tomorrow_humidity">Humidity</string>
fixed

2021-04-08 11:50 UTC, sin-al-vl approved these changes

2021-04-08 12:31 UTC, merged