Tomorrow weather forecast
AlexeyAnurin/WeatherAppInternship pull request #17
Opened 2021-04-09 12:34 UTC by AlexeyAnurin

2021-04-09 13:45 UTC, sin-al-vl requested changes

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/mapper/WeatherToDomainMapper.kt
> +            sunset = Date(it.sunsetTimeStampInSeconds * 1000),
Now it's definitely code duplication here. You need method `buildDateFromSeconds(int/long): Date` or smth like that  here

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStore.kt
> +    fun getCityCoordinates(): Flow<Pair<Double, Double>>
Why we didn't end up with coordinates object serialization? Is it impossible?
Methods signatures above unambiguously hints us that we need object here.

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/CityRepositoryImpl.kt
> +        return dataStore.getCityName().flowOn(Dispatchers.IO).distinctUntilChanged()
Too many method calls on one line

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/CityRepositoryImpl.kt
> +        return dataStore.getCityCoordinates().flowOn(Dispatchers.IO)
Do we need here `.distinctUntilChanged()` as well?

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherDailyModel.kt
> +)
I believe, this model is useless. It doesn't encapsulate anything, just creates additional level of nesting.
it might be replaced with `List<WeatherDailyDataModel>` everywhere. And then WeatherDailyDataModel may be simplified to WeatherDailyModel

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/repository/CityRepository.kt
> +    fun getCityCoordinates(): Flow<Pair<Double, Double>>
Repository should have our domain `LatLngModel` here, in both methods above.

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +            hourlyWeatherAdapter.setItems(it.weatherHourlyData.take(24))
Magic number. Create const val for it with self-explanatory name.

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherViewModel.kt
>      private val _weatherHourly = MutableLiveData<WeatherHourlyModel>()
About your if statement on the 29th line, it's quite artificial null safety behaviour. Why do we need this? You shouldn't call `.toString()` on nullable value in AppDataStoreImpl, just make getCityName return `Flow<String?>`

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherViewModel.kt
> +            cityRepository.getCityCoordinates().collect() {
studio warning

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherFragment.kt
> +            binding.tomorrowDateTextView.text = it.weatherDailyData[1]
Magic number again. But here it's strange, there is no way to justify its usage here. Why do we need daily weather on TomorrowWeatherFragment screen? We need here weather for tomorrow only. And its repository duty to distinguish data that we need from everything else.

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherFragment.kt
> +            hourlyWeatherAdapter.setItems(it.weatherHourlyData.takeLast(24))
magic number

2021-04-09 13:45 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherViewModel.kt
> +    init {
`init` shouldn't be before properties declaration in classes. Fix this everywhere.

2021-04-09 14:02 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/repository/CityRepository.kt
> +    fun getCityCoordinates(): Flow<Pair<Double, Double>>
fixed

2021-04-09 14:02 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/CityRepositoryImpl.kt
> +        return dataStore.getCityName().flowOn(Dispatchers.IO).distinctUntilChanged()
fixed

2021-04-09 14:08 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/mapper/WeatherToDomainMapper.kt
> +            sunset = Date(it.sunsetTimeStampInSeconds * 1000),
fixed

2021-04-09 14:13 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +            hourlyWeatherAdapter.setItems(it.weatherHourlyData.take(24))
fixed

2021-04-09 14:15 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherFragment.kt
> +            hourlyWeatherAdapter.setItems(it.weatherHourlyData.takeLast(24))
fixed

2021-04-09 14:17 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherViewModel.kt
> +    init {
fixed

2021-04-09 14:22 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherViewModel.kt
> +            cityRepository.getCityCoordinates().collect() {
I didnt get it.

2021-04-09 14:50 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherDailyModel.kt
> +)
Agree. Fixed.

2021-04-12 07:50 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/CityRepositoryImpl.kt
> +        return dataStore.getCityCoordinates().flowOn(Dispatchers.IO)
distinctUntilChanged() added

2021-04-12 08:03 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherViewModel.kt
>      private val _weatherHourly = MutableLiveData<WeatherHourlyModel>()
fixed

2021-04-12 14:43 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherDailyModel.kt
> +)
I applied a different solution where I need WeatherDailyModel class.

2021-04-12 14:45 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStore.kt
> +    fun getCityCoordinates(): Flow<Pair<Double, Double>>
I used object without any serialization: fun getCityCoordinates(): Flow<LatLngModel>

2021-04-12 14:57 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherFragment.kt
> +            binding.tomorrowDateTextView.text = it.weatherDailyData[1]
fixed

2021-04-12 16:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/mapper/WeatherToDomainMapper.kt
>  }
Timestamp usually given in millis. So my previous suggestion is still valid - buildDateFromSeconds

2021-04-12 16:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStoreImpl.kt
>              it[PreferencesKeys.CITY_KEY].toString()
You don't need `toString()` here now. 
Moreover, now this doesn't work as expected. This flow will never return `null` only string value `"null"`.

2021-04-12 16:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStoreImpl.kt
> +                it[PreferencesKeys.CITY_COORDINATES_LONGITUDE]!!
We'll definitely get a crash here, when you open this app at first time. You should have null checks here and return `Flow<LatLngModel?>`. This case is pretty similar to `getCityName()` logic here

2021-04-12 16:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +                WeatherDailyModel(result[TOMORROW_WEATHER], result)
We've discussed, that this should be treated in VM. And WeatherDailyModel still should be replaced with `List<WeatherDailyDataModel>`

2021-04-12 16:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +private const val HOURS_IN_DAY = 24
To VM

2021-04-12 16:18 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherViewModel.kt
>      private val _weatherHourly = MutableLiveData<WeatherHourlyModel>()
Not yet

2021-04-12 16:20 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherViewModel.kt
> +            cityRepository.getCityCoordinates().collect() {
I could see studio warning here about redundant braces.

2021-04-12 16:22 UTC, sin-al-vl requested changes

2021-04-12 16:22 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherFragment.kt
> +private const val HOURS_IN_DAY = 24
It's duplicate. Move this to DateUtils

2021-04-12 16:22 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherViewModel.kt
> +import javax.inject.Inject
A lot of unused imports

2021-04-12 16:47 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherViewModel.kt
> +import javax.inject.Inject
fixed

2021-04-12 16:50 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/mapper/WeatherToDomainMapper.kt
>  }
fixed

2021-04-12 16:52 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStoreImpl.kt
>              it[PreferencesKeys.CITY_KEY].toString()
Redundant toString() deleted.

2021-04-12 16:53 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +                WeatherDailyModel(result[TOMORROW_WEATHER], result)
done

2021-04-12 17:21 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStoreImpl.kt
> +                it[PreferencesKeys.CITY_COORDINATES_LONGITUDE]!!
When app is started at the first time there is default city, that gives us its coordinates.

2021-04-12 17:26 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +private const val HOURS_IN_DAY = 24
fixed

2021-04-13 07:08 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/tomorrowWeatherScreen/TomorrowWeatherFragment.kt
> +private const val HOURS_IN_DAY = 24
Moved to DateUtils.

2021-04-13 08:17 UTC, sin-al-vl requested changes

2021-04-13 08:17 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStoreImpl.kt
> +                it[PreferencesKeys.CITY_COORDINATES_LONGITUDE]!!
It's a mock temporary behavior. Later, when you'll implement empty city stub for UI, you won't have any default city. But there is no any guarantee that you'll come back to this place and fix it.
Main idea of my comment - this `!!` shouldn't be used here at all, since we may avoid its usage and it may cause NPE sooner or later. If don't have this problem now it doesn't mean that we'll never get it here.

2021-04-13 08:17 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenViewModel.kt
> +private const val TOMORROW = 1
TOMORROW_WEATHER_INDEX

2021-04-13 09:37 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/preferences/AppDataStoreImpl.kt
> +                it[PreferencesKeys.CITY_COORDINATES_LONGITUDE]!!
done

2021-04-13 09:37 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenViewModel.kt
> +private const val TOMORROW = 1
fixed

2021-04-13 11:12 UTC, sin-al-vl approved these changes

2021-04-13 12:35 UTC, merged