Week forecast screen, MainScreenViewModel with all view models.
AlexeyAnurin/WeatherAppInternship pull request #18
Opened 2021-04-14 12:05 UTC by AlexeyAnurin

![week forecast](https://user-images.githubusercontent.com/48724785/114707415-dc025c80-9d32-11eb-9ea1-53941e9a81e3.png)

2021-04-14 13:28 UTC, sin-al-vl requested changes

2021-04-14 13:28 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +        _binding = null
In destruction lifecycle methods `super.fun()` should be called in the very end of function

2021-04-14 13:28 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +            val currentDate = date.format(Date())
This and previous lines should be moved out to DateUtils

2021-04-14 13:28 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +private const val TODAY_DAY_OF_WEEK = "Today"
To resources!

2021-04-14 13:28 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +                , weatherDailyData.nightTemperature
?

2021-04-14 13:28 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +            val date = SimpleDateFormat(DAY_MONTH_DATE_PATTERN)
Studio has warning here for you. Use Locale

2021-04-14 13:28 UTC, sin-al-vl commented on app/src/main/res/values/strings.xml
> +    <string name="precipitation_pattern">%1$s %%</string>
This is the duplicate of the previous line.

2021-04-14 13:29 UTC, sin-al-vl commented
Dagger setup is completely wrong. Let's discuss it personally

2021-04-14 16:26 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
> +        _binding = null
fixed

2021-04-14 16:33 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +                , weatherDailyData.nightTemperature
fixed

2021-04-14 16:34 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +            val date = SimpleDateFormat(DAY_MONTH_DATE_PATTERN)
Already used.

2021-04-15 08:00 UTC, AlexeyAnurin commented on app/src/main/res/values/strings.xml
> +    <string name="precipitation_pattern">%1$s %%</string>
fixed

2021-04-15 08:00 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +            val date = SimpleDateFormat(DAY_MONTH_DATE_PATTERN)
fixed

2021-04-15 08:04 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +private const val TODAY_DAY_OF_WEEK = "Today"
fixed

2021-04-15 08:10 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/weekWeatherScreen/WeekWeatherAdapter.kt
> +            val currentDate = date.format(Date())
fixed

2021-04-15 14:26 UTC, sin-al-vl approved these changes

2021-04-15 14:26 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/di/MainScreenSubComponent.kt
> +class MainScreenSubComponent
It seems like everything cool with dagger now. You need just a small clean up.
I've recommended you to name Fragment component by feature name (e.g. ForecastComponent). You've confused yourself with current names. Have a look at your `di` package attentively. You'll find out that each component (except fragment component) should have a corresponding `...SubComponent`. `AppComponent` has `AppSubComponents`, `MainActivityComponent` has.... `MainScreenSubComponent`, `MainScreenComponent` doesn't have subcomponents. Do you see flaw in this chain?
Firstly, MainScreenSubComponent is actually MainActivitySubComponent. Also you should decide wether your subcomponents should be named in singular or plural forms. And last but not least thing - why do they all placed in the same package? Each component may be in separate package - app/activity/fragment

2021-04-15 14:26 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
>  package com.griddynamics.weatherappinternship.presentation.currentWeatherScreen
One more recommendation about packaging. 
Firstly, your packages have both camel case (currentWeatherScreen) and lower case (weatherappinternship). I'd recommend to use lower case only. And in order to simplify package names, I'd delete `Screen` word from all packages, except `mainscreen`.
Secondly, according to our latest changes `mainscreen` and all other fragment are not equal. So they shouldn't be on the same package lvl. `current`, `tomorrow` and `week` packages should be inside `mainscreen` package since they are an integral part of it. Thus, `HourlyWeatherAdapter` should also be in `mainscreen` package.

2021-04-15 14:56 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/currentWeatherScreen/CurrentWeatherFragment.kt
>  package com.griddynamics.weatherappinternship.presentation.currentWeatherScreen
Understood. Done.

2021-04-15 16:02 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/di/MainScreenSubComponent.kt
> +class MainScreenSubComponent
Done

2021-04-15 16:03 UTC, merged