Empty city stub
AlexeyAnurin/WeatherAppInternship pull request #19
Opened 2021-04-15 16:18 UTC by AlexeyAnurin

2021-04-15 18:05 UTC, sin-al-vl requested changes

2021-04-15 18:05 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenViewModel.kt
> +
?

2021-04-15 18:05 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenViewModel.kt
> +    internal val haveNoSavedCity = SingleLiveEvent<Unit>()
Do we really need two liveDatas? Why we cannot use one liveData with boolean value?
Also it'd better change `have` to `has` since implied subject is `it`

2021-04-15 18:05 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +            binding.viewPager.visibility = GONE
It's code duplication here. This two lines should be moved to separate method. But if you'll combine liveDatas, this problem will gone by itself.

2021-04-16 10:12 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +            binding.viewPager.visibility = GONE
fixed

2021-04-16 10:12 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenViewModel.kt
> +    internal val haveNoSavedCity = SingleLiveEvent<Unit>()
fixed

2021-04-16 10:12 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenViewModel.kt
> +
fixed

2021-04-16 10:15 UTC, sin-al-vl approved these changes

2021-04-16 10:23 UTC, merged