current weather info
AlexeyAnurin/WeatherAppInternship pull request #5
Opened 2021-03-22 14:10 UTC by AlexeyAnurin

2021-03-22 14:48 UTC, sin-al-vl requested changes

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/di/AppModule.kt
> +    @PerApplication
Justify this annotation here, please. Why do you think, MainScreenViewModel should be scopped to the App level?
One more thing: you've missed scope annotation in `RepositoryModule` for `WeatherRepository`.

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/interceptors/ApiKeyInterceptor.kt
> +                .addQueryParameter(UNITS, CELSIUS)
Class called `ApiKeyInterceptor`, but now we work with metric here. Don't you find this confusing?

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherModel.kt
>  @JsonClass(generateAdapter = true)
Domain layer shouldn't know anything about any frameworks (Moshi in this case).

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/MainActivity.kt
> +        val sectionsPagerAdapter = SectionsPagerAdapter(this, supportFragmentManager)
It's cheating) Current weather info ticket doesn't imply any pager adapter implementation. You've mixed here another task that you even don't have on the board yet.

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/MainActivity.kt
> +        sv_city_search.setOnQueryTextListener(object : android.widget.SearchView.OnQueryTextListener {
You should mention in the MR description, that `Place search by name` is also implemented here. Now it looks confusing to me.
By the way, your commit message is also quite confusing and misleading.

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/SectionsPagerAdapter.kt
> +private val TAB_TITLES = arrayOf(
Check previous comments.

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +                            "${it.weather[0].weatherIcon}@2x.png")
I believe, this url should be formed somewhere on the repo lvl.

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/ab_appBar"
What `ab` prefix means? It's not obvious foe me

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/sv_city_search"
If `sv` means `search view`, I'd say that suffix `search` is redundant

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/tabs"
AppBarLayout has one principle of the id name forming. TabLayout has another principle. It's different UI elements, but they are both layouts. Please, be consistent in naming policy.

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/res/layout/activity_main.xml
> +                app:tabBackground="@color/background_tabLayout"
Camel case + snake case in the same ref name. This is unacceptable

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/res/layout/fragment_mainscreen.xml
> +        android:layout_marginTop="16dp"
If you see frequently used indentations, please, move their values to `dimens`

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/res/layout/fragment_mainscreen.xml
> +        android:text="Date &amp; Time"
string res

2021-03-22 14:48 UTC, sin-al-vl commented on app/src/main/res/values/strings.xml
> +    <string name="feels_like">Ощущается как</string>
Quite unexpectedly. What Russian text does among English string values?

2021-03-23 07:44 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/interceptors/ApiKeyInterceptor.kt
> +                .addQueryParameter(UNITS, CELSIUS)
Separate UnitsInterceptor created. fixed.

2021-03-23 07:46 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherModel.kt
>  @JsonClass(generateAdapter = true)
Dto class with moshi annotation created. Values mapped to domain model.

2021-03-23 07:53 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +                            "${it.weather[0].weatherIcon}@2x.png")
I didnt find another place for url building, but buit it with constants.

2021-03-23 08:34 UTC, AlexeyAnurin commented on app/src/main/res/layout/fragment_mainscreen.xml
> +        android:text="Date &amp; Time"
fixed

2021-03-23 08:34 UTC, AlexeyAnurin commented on app/src/main/res/layout/fragment_mainscreen.xml
> +        android:layout_marginTop="16dp"
fixed

2021-03-23 08:35 UTC, AlexeyAnurin commented on app/src/main/res/values/strings.xml
> +    <string name="feels_like">Ощущается как</string>
fixed

2021-03-23 08:37 UTC, AlexeyAnurin commented on app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/sv_city_search"
fixed

2021-03-23 09:05 UTC, AlexeyAnurin commented on app/src/main/res/layout/activity_main.xml
> +                app:tabBackground="@color/background_tabLayout"
fixed

2021-03-23 09:06 UTC, AlexeyAnurin commented on app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/tabs"
fixed

2021-03-23 09:09 UTC, AlexeyAnurin commented on app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/sv_city_search"
I would name in "city_search_view"

2021-03-23 09:12 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +                            "${it.weather[0].weatherIcon}@2x.png")
I would name in "appbar_layout"

2021-03-23 09:12 UTC, AlexeyAnurin commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/ab_appBar"
I would name in "appbar_layout"

2021-03-23 09:49 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/di/AppModule.kt
> +    @PerApplication
I have added MainActivityComponent as a SubComponent for scope @PerActivity to scope there ViewModel.

2021-03-23 10:15 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/MainActivity.kt
> +        val sectionsPagerAdapter = SectionsPagerAdapter(this, supportFragmentManager)
Deleted from this PR

2021-03-23 10:15 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/MainActivity.kt
> +        sv_city_search.setOnQueryTextListener(object : android.widget.SearchView.OnQueryTextListener {
Deleted from this PR

2021-03-23 10:15 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/SectionsPagerAdapter.kt
> +private val TAB_TITLES = arrayOf(
Deleted from this PR

2021-03-23 11:39 UTC, sin-al-vl requested changes

2021-03-23 11:39 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +data class Coordinates(
Naming consistency. If this is a network DTO, class name should ends with Dto as well

2021-03-23 11:39 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +}
As I said earlier, this function should be moved out to the separate file in `network.mapper` package.

2021-03-23 11:39 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +data class WeatherModelDto(
`internal`. The same for all classes in this package

2021-03-23 11:39 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +                .toDomain()
That's exact case, where `.toDomain` should stay on the previous line

2021-03-23 11:39 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +private const val BASE_WEATHER_ICON_PROPERTIES = "@2x.png"
What would you do, when there will be need to display such icon on another fragment? This should be moved to mapper. And `BASE_WEATHER_ICON_URL + it.weatherIcon + BASE_WEATHER_ICON_PROPERTIES` transformation should be there as well.

2021-03-23 11:39 UTC, sin-al-vl commented on app/src/main/res/values/strings.xml
> +    <string name="tab_text_3">TAB_3</string>
Why do we need this strings?

2021-03-23 11:44 UTC, sin-al-vl requested changes

2021-03-23 11:44 UTC, sin-al-vl commented on app/src/main/res/values/strings.xml
> +    <string name="format24Hour">EEEE, MMMM dd, yyyy h:mmaa</string>
Such patterns should be marked with `translatable="false"`. And it's better to keep them in separate string res file with the name `donottranslate.xml`, for example

2021-03-23 13:16 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +data class Coordinates(
fixed

2021-03-23 13:24 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/repository/WeatherRepositoryImpl.kt
> +                .toDomain()
fixed

2021-03-23 13:27 UTC, AlexeyAnurin commented on app/src/main/res/values/strings.xml
> +    <string name="tab_text_3">TAB_3</string>
Fixed.

2021-03-23 13:42 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +data class WeatherModelDto(
When I mark classes as internal, an error comes
![image](https://user-images.githubusercontent.com/48724785/112155889-6bae6280-8bee-11eb-8490-4455e85de884.png)

2021-03-23 13:54 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +}
fun WeatherModelDto.toDomain() is transferred to file WeatherToDomainMapper in network.mapper package.

2021-03-23 14:03 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +private const val BASE_WEATHER_ICON_PROPERTIES = "@2x.png"
Extension function for building icon url is added to mapper.

2021-03-23 14:09 UTC, AlexeyAnurin commented on app/src/main/res/values/strings.xml
> +    <string name="format24Hour">EEEE, MMMM dd, yyyy h:mmaa</string>
fixed

2021-03-23 15:09 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +data class WeatherModelDto(
WeatherApi should be internal as well. And so, and so...

2021-03-23 16:26 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/data/network/model/WeatherModelDto.kt
> +data class WeatherModelDto(
fixed

2021-03-23 17:20 UTC, sin-al-vl requested changes

2021-03-23 17:20 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +private const val BASE_WEATHER_ICON_PROPERTIES = "@2x.png"*/
no way

2021-03-23 17:20 UTC, sin-al-vl commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherModel.kt
> +    val weatherIcon: String,
weatherIconUrl

2021-03-23 17:27 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/presentation/mainScreen/MainScreenFragment.kt
> +private const val BASE_WEATHER_ICON_PROPERTIES = "@2x.png"*/
fixed

2021-03-23 17:28 UTC, AlexeyAnurin commented on app/src/main/java/com/griddynamics/weatherappinternship/domain/model/WeatherModel.kt
> +    val weatherIcon: String,
fixed

2021-03-24 09:42 UTC, merged